name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build TinyPDF
        run: xcodebuild clean build -project TinyPDF.xcodeproj -scheme TinyPDF -configuration Release -derivedDataPath /tmp/tinybuild/tinypdf CODE_SIGN_IDENTITY="-"
